### PR TITLE
Russian language

### PR DESCRIPTION
**Pull request by DearFox**
Translation of the names items and blocks into Russian.

### CODE REVIEW

**Comment by PortableGames** [comment]
Слава Україні! Героям слава!

**Comment by DearFox** [comment]
> Слава Україні! Героям слава!

I think I could also do a translation into Ukrainian if there is demand.

**Comment by MushroomMif** [comment]
Btw there is already a translation of this mod in Russian on Patbox's Crowdin: https://crowdin.com/project/patbox-mods

And also, in Russian only the first letter of name should be in upper case, not the first letter of every word (how it works in English)
Example: You translated "Birch Shelf" as "Берёзовая Полка" but it should be "Берёзовая полка". 
You can look at Minecraft's Russian translation, it works there in the same way

**Comment by DearFox** [comment]
> ~Btw there is already a translation of this mod in Russian on Patbox's Crowdin~ Oh, you already discussed this with Patbox in his discord
> 
> And also, in Russian only the first letter of name should be in upper case, not the first letter of every word (how it works in English) Example: You translated "Birch Shelf" as "Берёзовая Полка" but it should be "Берёзовая полка". You can look at Minecraft's Russian translation, it works there in the same way

I thought it was some kind of writing style
 But this is easy to fix.

**Pull request closed without merging**
